### ISSUE TITLE
How to handle Response from CCS end point.

### ISSUE THREAD

**Issue by rajeevinimekumar008** [kikinteractive/go-gcm#18]
Hi i am new to GO lang. Is there any sample example illustrating how to use this package for XMPP protocol. 

I have previously used SMACK (JAVA) API successfully.

**Comment by rajeevinimekumar008** [comment]
I have managed to write a simple GO Lang program that pushes the notification to devices.. 

But due to lack of proper documentation.. I could not find the what actually the return type of `sendXmpp` method defines.

In my case i m getting `1, 313 and <nil>` respectively as return from this method.
But what it actually defines ?

How can i handle `Connection Draining` and `Acknowledgement` from server.. ?

Please let me know !!!

**Comment by bolshoy** [comment]
Hi. The code is pretty self explaining, and you just read it. In your case, see where SendXMPP is implemented, it's in https://github.com/kikinteractive/go-gcm/blob/master/client.go#L91
Then, you see that it's implemented in XMPP client https://github.com/kikinteractive/go-gcm/blob/master/xmpp.go#L307
Reading this code, you see that the first return value is messageID, the second is number of bytes sent and the third is the error.
You don't need to handle connection draining and acknowledgements, they are already handled. 
Please next time read the code before you ask these questions.
