### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by karapas** [kikinteractive/go-gcm#23]
Hi folks,

I am trying to install go-gcm using "go get github.com/kikinteractive/go-gcm" and i get the following error:
`
src/github.com/kikinteractive/go-gcm/xmpp.go:118: cannot use nc (type *xmpp.Client) as type xmppClient in field value:
	*xmpp.Client does not implement xmppClient (missing JID method)
`

My go version is:

go version go1.7.5 darwin/amd64

Am I doing anything really stupid? Any help would be appreciated.

Thanks!

**Comment by bolshoy** [comment]
@karapas maybe you have an older version of https://github.com/mattn/go-xmpp.
generally it's recommended to use glide for your projects.
you can also do `go get -u ...`

**Comment by karapas** [comment]
@bolshoy yes you are right. Had google's go-gcm package installed which depends on go-xmpp package as well. Updated and everything works now! Thanks a lot!

Btw, one quick, off-topic question: from what i understand i can use a single gcm.Client for my entire application, ie multiple goroutines can use the same client to send out gcm messages. Am i correct?

Thanks a lot once again!

**Comment by bolshoy** [comment]
correct, the gcm client is thread safe, so no need to guard it with mutexes.
