### ISSUE TITLE
Should not put logging implementation

### ISSUE THREAD

**Issue by uudashr** [kikinteractive/go-gcm#31]
IMHO Should not add logging implementation (logrus) since the actual user might use different logging library such as https://github.com/uber-go/zap.

See https://www.slf4j.org/faq.html#when
> In short, libraries and other embedded components should consider SLF4J for their logging needs because libraries cannot afford to impose their choice of logging framework on the end-user.

In Golang, simply provide logging interface which defaulting to standard Golang logging API would be wise, since there is no require any additional dependency.

**Comment by bolshoy** [comment]
unfortunately, different loggers have different signatures (for example, logrus and go-kit), so the standard logging API will limit the metadata you want to output. So the question is what kind of a logging interface to accept. Currently, a simple method is used, if you want something else please provide a PR.
